export const localGpus = [
  {
    name: "GeForce RTX 5090",
    arch: "Blackwell (GB202)",
    vram: "32 GB GDDR7",
    vramGb: 32,
    bandwidth: "1.79 TB/s",
    bandwidthTbps: 1.79,
    tgp: "575W",
    tgpWatts: 575,
    price: "₹4.98L - ₹7.50L",
    priceMin: 498000,
    gpuClass: "Flagship Consumer",
    features: { nvlink: false, ecc: false, memoryType: "GDDR7" },
  },
  {
    name: "GeForce RTX 4090",
    arch: "Ada (AD102)",
    vram: "24 GB GDDR6X",
    vramGb: 24,
    bandwidth: "1.00 TB/s",
    bandwidthTbps: 1.0,
    tgp: "450W",
    tgpWatts: 450,
    price: "₹1.72L - ₹2.62L",
    priceMin: 172000,
    gpuClass: "Previous Gen King",
    features: { nvlink: false, ecc: false, memoryType: "GDDR6X" },
  },
  {
    name: "GeForce RTX 5080",
    arch: "Blackwell (GB203)",
    vram: "16 GB GDDR7",
    vramGb: 16,
    bandwidth: "896 GB/s",
    bandwidthTbps: 0.896,
    tgp: "360W",
    tgpWatts: 360,
    price: "₹1.50L - ₹2.62L",
    priceMin: 150000,
    gpuClass: "High-End Consumer",
    features: { nvlink: false, ecc: false, memoryType: "GDDR7" },
  },
  {
    name: "Enterprise L40S",
    arch: "Ada (AD102)",
    vram: "48 GB ECC",
    vramGb: 48,
    bandwidth: "864 GB/s",
    bandwidthTbps: 0.864,
    tgp: "350W",
    tgpWatts: 350,
    price: "₹5.75L - ₹8.14L",
    priceMin: 575000,
    gpuClass: "Enterprise Inference",
    features: { nvlink: false, ecc: true, memoryType: "GDDR6" },
  },
  {
    name: "Enterprise H100",
    arch: "Hopper (GH100)",
    vram: "80 GB HBM3",
    vramGb: 80,
    bandwidth: "3.35 TB/s",
    bandwidthTbps: 3.35,
    tgp: "700W",
    tgpWatts: 700,
    price: "₹35L+",
    priceMin: 3500000,
    gpuClass: "Datacenter Standard",
    features: { nvlink: true, ecc: true, memoryType: "HBM3" },
  },
  {
    name: "Enterprise H200",
    arch: "Hopper (GH100)",
    vram: "141 GB HBM3e",
    vramGb: 141,
    bandwidth: "4.80 TB/s",
    bandwidthTbps: 4.8,
    tgp: "700W",
    tgpWatts: 700,
    price: "₹45L+",
    priceMin: 4500000,
    gpuClass: "LLM Training Apex",
    features: { nvlink: true, ecc: true, memoryType: "HBM3e" },
  },
];

export const cloudProviders = [
  {
    provider: "Vast.ai",
    gpu: "RTX 5090",
    rate: "~$0.41 - $0.48",
    rateUsdHr: 0.45,
    billing: "USD / Hourly",
    profile: "Interruptible / Fault-tolerant R&D, Academic",
    tier: "budget",
    region: "Global",
  },
  {
    provider: "RunPod",
    gpu: "H200 (141GB)",
    rate: "~$4.39",
    rateUsdHr: 4.39,
    billing: "USD / Hourly",
    profile: "On-Demand / Serverless inference, fine-tuning",
    tier: "premium",
    region: "Global",
  },
  {
    provider: "Lambda Labs",
    gpu: "H100 SXM",
    rate: "~$3.99",
    rateUsdHr: 3.99,
    billing: "USD / Hourly",
    profile: "On-Demand / Persistent multi-week training",
    tier: "premium",
    region: "Global",
  },
  {
    provider: "E2E Networks",
    gpu: "H200 (141GB)",
    rate: "₹88 (~$1.05)",
    rateUsdHr: 1.05,
    billing: "INR / Hourly",
    profile: "Preemptible Spot / Massive batch processing (Local)",
    tier: "mid",
    region: "India",
  },
  {
    provider: "Cyfuture",
    gpu: "L40S (48GB)",
    rate: "₹61 (~$0.72)",
    rateUsdHr: 0.72,
    billing: "INR / Hourly",
    profile: "On-Demand / High-uptime enterprise inference",
    tier: "budget",
    region: "India",
  },
  {
    provider: "AceCloud",
    gpu: "L40S (48GB)",
    rate: "₹115 (~$1.36)*",
    rateUsdHr: 1.36,
    billing: "INR / Monthly (₹83k)",
    profile: "Monthly Reserve / Predictable OpEx mapping",
    tier: "mid",
    region: "India",
  },
];

export const integratedSystems = [
  {
    type: "Flagship Gaming Laptop",
    gpu: "RTX 5090 Mobile",
    specs: "24GB VRAM | Up to 175W TGP",
    price: "₹3.99L - ₹8.39L",
    priceMin: 399000,
    limit: "Severe thermal throttling under sustained load.",
    icon: "💻",
    formFactor: "laptop",
  },
  {
    type: "Custom AI Workstation",
    gpu: "1x Desktop RTX 5090",
    specs: "32GB VRAM | 575W TGP | 128GB RAM",
    price: "~₹6.50L",
    priceMin: 650000,
    limit: "High initial CapEx, requires 1000W+ PSU.",
    icon: "🖥️",
    formFactor: "workstation",
  },
  {
    type: "Dual-GPU Research Rig",
    gpu: "2x Desktop RTX 5090",
    specs: "64GB VRAM | 1150W TGP Combined",
    price: "~₹11.00L+",
    priceMin: 1100000,
    limit: "Requires dedicated 15A electrical circuits.",
    icon: "⚡",
    formFactor: "workstation",
  },
  {
    type: "Enterprise OEM Desktop",
    gpu: "1x RTX 6000 Ada",
    specs: "48GB VRAM | 300W TGP",
    price: "₹8.00L - ₹10.00L+",
    priceMin: 800000,
    limit: "High 'corporate tax', lower raw compute vs consumer.",
    icon: "🏢",
    formFactor: "desktop",
  },
];
